[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.22"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# remappings = [
#     # note: map to package level only, required for pnp-berry to work with foundry
#     # ok - solidity-stringutils/=node_modules/solidity-stringutils/
#     # not ok - solidity-stringutils/=node_modules/solidity-stringutils/src/
#     '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
#     '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
#     '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
#     '@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/',
#     '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
# ]
